# Generated by Django 4.1.1 on 2022-09-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_image_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="name",
            field=models.CharField(default=1, max_length=50, verbose_name="Название"),
            preserve_default=False,
        ),
    ]
