# Generated by Django 3.2.9 on 2022-09-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_image_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
